### ISSUE TITLE
Scope section of the wiki.

### ISSUE THREAD

**Issue by Johndh27** [MedicalAppCSUFresno/MedicalApp#11]
Being given the Scope section of the wiki, let me know if it feels incomplete to any of you, and I'll edit and adjust it. 

As of now, it may be the finalized text.

**Comment by zappykidd** [comment]
I think my only issue would be the random line in our Use Case diagram. We might be graded harshly on that. Shouldn't take long to fix it.

**Comment by Jonze96** [comment]
Looks good.
