### ISSUE TITLE
Next Meeting

### ISSUE THREAD

**Issue by Johndh27** [MedicalAppCSUFresno/MedicalApp#26]
Hello all, when and where would you all want to meetup to update each other/work together again these coming days? Let's plan it.

Just a heads up Jesus, next time we meet, you want to show me how to connect the buttons to other activities/pages? Also on how to make button icons. I saw some videos, but they didn't utilize png files in the drawable folder, and instead used uploaded png files into xml files. 

If you got the video saved on youtube, you can just linked it down below too.

**Comment by Johndh27** [comment]
I should be free after lab class for 150 on Tuesday. And maybe in the late evening of Wednesday. Let me know if any of you want to meet up. 

Just an update, our presentation is in 3 days.

**Comment by zappykidd** [comment]
I'm fine with this. I have meetings both at 7 pm today and tomorrow. Besides that, I'm available.

**Comment by Johndh27** [comment]
Meeting is at 3:15pm on 12/5/2018. This issue will be closed now.
