### ISSUE TITLE
Edit Profile Button

### ISSUE THREAD

**Issue by zappykidd** [MedicalAppCSUFresno/MedicalApp#31]
Goal is to be able to update the Firebase database with new information.

Making this requires a new page in the app (not everything is being updated). The only thing that is remaining is the same is the email.

**Comment by zappykidd** [comment]
The new page has been made. Just needs to communicate with the database and the button.

**Comment by jcovarrubias11** [comment]
I have created and linked the page with the database it all should be working okay
