### ISSUE TITLE
Design a database

### ISSUE THREAD

**Issue by jcovarrubias11** [MedicalAppCSUFresno/MedicalApp#6]
get the mongo DB set up

**Comment by zappykidd** [comment]
The database is created locally on my laptop. Now I need to have it uploaded to Android Studio and push it to my branch to the merge it to the master branch.

**Comment by zappykidd** [comment]
Database was changed from MongoDB to Firebase.

**Comment by jcovarrubias11** [comment]
Created database and linked it to the application
